#!/bin/zsh -x

source ./common
fail_if_not_populated APP_ROOT APP_MARK_EXEC_LOC

if [[ ! -f "$APP_MARK_EXEC_LOC" ]]; then
    pushd "${APP_ROOT}"
        find . -type f -print0 \
            | xargs -0 file \
            | grep "executable\|ELF\|LSB" \
            | cut -d":" -f1 > "$APP_MARK_EXEC_LOC"
    popd
fi

source ./common
fail_if_not_populated APP_MARK_EXEC

cd "${APP_ROOT}"
echo "$APP_MARK_EXEC" | xargs chmod +x

exit 0
