#!/bin/zsh -x

if [[ ! -d "apps/${APP}.dlc/" ]]; then
    echo "Place dlcs in ./apps/{appname}/dlc folder (might have to create folder manually)"
    exit
fi

./install || exit $?
source ./common

fail_if_not_populated APP APP_ROOT

[[ -d "${APP_ROOT}/dlc" ]] \
    && mv "${APP_ROOT}/dlc"{,.old}

mkdir "${APP_ROOT}/dlc/"
cp -r "apps/${APP}/dlc/"* "${APP_ROOT}/dlc/"
