#!/bin/zsh -x

source ./common
fail_if_not_populated APP APP_ROOT GOLDBERG_BUILD

pushd goldberg_emulator
make clean -j4 || exit $?
make -j4 "$GOLDBERG_BUILD" || exit $?
[[ ! -f libsteam_api.so ]] && exit 1
popd

./reset || exit $?
./chmod_files || exit $?
"./apps/${APP}/override_prep" || exit $?

source ./common
fail_if_not_populated OVERRIDE_DIRS

install_at() {
    ./md5output "$1"

    mv "$1/libsteam_api.so"{,.old}

    cp goldberg_emulator/libsteam_api.so "$1/libsteam_api.so"
    cp "./apps/${APP}/steam_settings" "$1/" -r

    ./md5output "$1"
}

for OVERRIDE_DIR in "${OVERRIDE_DIRS[@]}"; do
    [[ -d "${OVERRIDE_DIR}" ]] \
        && install_at "${OVERRIDE_DIR}"
done
