#!/bin/zsh -x

source ./common

uninstall_at() {
    [[ -f "$1/libsteam_api.so.old" ]] \
        && mv "$1/libsteam_api.so"{.old,}

    [[ -d "$1/steam_settings" ]] \
        && rm "$1/steam_settings" -rf
}

for OVERRIDE_DIR in "${OVERRIDE_DIRS[@]}"; do
    [[ -d "${OVERRIDE_DIR}" ]] \
        && uninstall_at "${OVERRIDE_DIR}"
done

if [[ -d "${APP_ROOT}" && -d "${APP_ROOT}/dlc.old" ]]; then
    [[ -d "${APP_ROOT}/dlc" ]] \
        && rm "${APP_ROOT}/dlc" -rf
    mv "${APP_ROOT}/dlc"{.old,}
fi

"./apps/${APP}/override_undo"

exit 0
