#!/bin/zsh -x

source ./common

[[ -d "${LAUNCHER_API_LOC}" ]] \
    && rm -rf "$HOME/.paradoxlauncher" 

[[ -f .launcher_version ]] \
    && rm apps/eu4/.launcher_version 

./run

while true do
    echo "Sleeping for 10 seconds..."
    sleep 10
    basename "$(echo "$HOME/.paradoxlauncher/launcher-"*)" > ./apps/eu4/.launcher_version
    source ./common
    [[ -d "${LAUNCHER_API_LOC}" ]] && break
    echo "Launcher not found, retrying."
done

exit 0
